config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  mount Resque::Server.new, at: '/resque' if Rails.env.development?

  resource :import_checks, only: :index do
    get :index
    post :dropbox
  end

  resource :exports, only: %i( create ) do
    get :index
  end

  namespace :users do
    get ':id/wait_for_confirmation', to: 'messages#wait_for_confirmation', as: :wait_for_confirmation
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', as: :new_user_session
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  root to: 'check_images#index'

  resources :check_images, except: %i( show )
  resources :checks, only: %i( create update )
  resources :roles
end

app/models/role.rb
# == Schema Information
#
# Table name: roles
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Role < ActiveRecord::Base
  schema_validations
  schema_associations

  ROLE_NAMES = %i( guest unconfirmed employee admin )

  ROLE_NAMES.each do |name|
    scope name.to_s.pluralize, -> { where Role.arel_table[:name].matches(name) }
  end

  class << self
    ROLE_NAMES.each do |name|
      define_method(name) { send(name.to_s.pluralize).first }
    end
  end

  def confirmed?
    name.downcase != unconfirmed_name
  end

  private

    def unconfirmed_name
      unconfirmed = self.class.unconfirmed
      unconfirmed = (unconfirmed.respond_to?(:first) ? unconfirmed.first : unconfirmed)
      unconfirmed.present? ? unconfirmed.name.downcase : nil
    end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @roles = Role.all
    respond_with(@roles)
  end

  def show
    respond_with(@role)
  end

  def new
    @role = Role.new
    respond_with(@role)
  end

  def edit
  end

  def create
    @role = Role.new(role_params)
    @role.save
    respond_with(@role)
  end

  def update
    @role.update(role_params)
    respond_with(@role)
  end

  def destroy
    @role.destroy
    respond_with(@role)
  end

  private
    def set_role
      @role = Role.find(params[:id])
    end

    def role_params
      params.require(:role).permit(:name, :users)
    end
end

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :users %><br>
    <%= f.text_field :users %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<h1>Listing roles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Users</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= role.users %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<p>
  <strong>Users:</strong>
  <%= @role.users %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>