config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  mount Resque::Server.new, at: '/resque' if Rails.env.development?

  resource :import_checks, only: :index do
    get :index
    post :dropbox
  end

  resource :exports, only: %i( create ) do
    get :index
  end

  namespace :users do
    get ':id/wait_for_confirmation', to: 'messages#wait_for_confirmation', as: :wait_for_confirmation
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', as: :new_user_session
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  root to: 'check_images#index'

  resources :check_images, except: %i( show )
  resources :checks, only: %i( create update )
  resources :roles
end

app/models/export.rb
class Export
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  def persisted?
    persisted
  end

	attr_reader :checks, :check_ids
  attr_accessor :persisted
  private :persisted, :persisted=

	def initialize(check_ids=nil)
		@checks = check_ids.blank? ? Check.not_exported : Check.not_exported.where(id: check_ids)
    @persisted = false
  end

  def save
    exporter.export checks
  end

  private

  def exporter
    @exporter ||= Exporter.new
  end
end

app/controllers/exports_controller.rb
class ExportsController < ApplicationController
  respond_to :html

  def index
    @export = Export.new
  end

  def create
    @export = Export.new export_params[:check_ids]
    @export.save
  rescue HomeFinanceAPI::Client::NoConnectionException => ex
    flash[:error] = 'It\'s a pity:( Seems we have no connection at the moment and can\'t send your data to server. '
  ensure
    respond_with @export
  end

  private

    def export_params
      params.require(:export)
            .permit(check_ids: [])
            .tap { |this| this['check_ids'].reject! { |i| i == '0' } }
    end
end

app/views/exports/_form.html.erb
<%= form_for(@export) do |f| %>
  <% if @export.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@export.errors.count, "error") %> prohibited this export from being saved:</h2>

      <ul>
      <% @export.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :index %><br>
    <%= f.text_field :index %>
  </div>
  <div class="field">
    <%= f.label :create %><br>
    <%= f.text_field :create %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exports/edit.html.erb
<h1>Editing export</h1>

<%= render 'form' %>

<%= link_to 'Show', @export %> |
<%= link_to 'Back', exports_path %>

app/views/exports/index.html.erb
<h1>Export</h1>

<%= form_for @export do |f| %>
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Comment</th>
        <th>Amount</th>
        <th>Category</th>
        <th>Currency</th>
        <th>Account</th>
      </tr>
    </thead>

    <tbody>
      <%= render @export.checks, f: f %>
    </tbody>
  </table>

  <%= f.submit 'New Export' %>
<% end %>

app/views/exports/new.html.erb
<h1>New export</h1>

<%= render 'form' %>

<%= link_to 'Back', exports_path %>

app/views/exports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Index:</strong>
  <%= @export.index %>
</p>

<p>
  <strong>Create:</strong>
  <%= @export.create %>
</p>

<%= link_to 'Edit', edit_export_path(@export) %> |
<%= link_to 'Back', exports_path %>